# Generated by Django 5.2.5 on 2025-08-12 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название организации')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('contact_person', models.CharField(max_length=255, verbose_name='Контактное лицо')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Контактный телефон')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(verbose_name='Дата проведения ТО')),
                ('operating_hours', models.PositiveIntegerField(verbose_name='Наработка, м/час')),
                ('work_order_number', models.CharField(max_length=50, verbose_name='№ заказ-наряда')),
                ('work_order_date', models.DateField(verbose_name='Дата заказ-наряда')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_services', to='monitoring.machine', verbose_name='Машина')),
                ('service_company', models.ForeignKey(blank=True, limit_choices_to={'role': 'service'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания')),
                ('service_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitoring.serviceorganization', verbose_name='Организация, проводившая ТО')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitoring.servicetype', verbose_name='Вид ТО')),
            ],
        ),
    ]
