# Generated by Django 5.2.5 on 2025-08-15 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_failurenode_recoverymethod_reclamation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['-shipment_date']},
        ),
        migrations.AlterModelOptions(
            name='reclamation',
            options={'ordering': ['-failure_date']},
        ),
        migrations.AlterModelOptions(
            name='technicalservice',
            options={'ordering': ['-service_date']},
        ),
    ]
