# Generated by Django 5.2.5 on 2025-09-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_reference_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('service', 'Сервисная организация'), ('manager', 'Менеджер ЧЗСА')], default='client', max_length=20),
        ),
    ]
