# Generated by Django 5.2.5 on 2025-09-06 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_alter_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
