# Generated by Django 5.2.5 on 2025-09-06 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_delete_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Maintenance',
        ),
    ]
