# Generated by Django 5.2.5 on 2025-09-07 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalservice',
            name='service_organization_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название организации (текст, если не в справочнике)'),
        ),
        migrations.AlterField(
            model_name='technicalservice',
            name='service_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='monitoring.serviceorganization', verbose_name='Организация, проводившая ТО'),
        ),
    ]
